name: 'Load Data from GitHub Action'

on:
  push:
    branches:
      - main

jobs:
  upload_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload Data to Databricks
        run: |
          # Set up Databricks CLI (dbx)
          pip install databricks-cli

          # Configure Databricks CLI
          dbx configure --url "https://2802865079231275.5.gcp.databricks.com/recents?o=2802865079231275"

          # Upload data to Databricks
          dbx fs cp --recursive data/sample.txt