name: Send Data to Databricks

on:
  push:
    branches:
      - main

jobs:
  send_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Databricks CLI (dbx)
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          dbx configure --url "https://2802865079231275.5.gcp.databricks.com/recents?o=2802865079231275#"

      - name: Send Data to Databricks Workspace
        run: |
          dbx fs cp --recursive path/to/data/ dbfs:/mnt/sample.txt
